const FOCUS_SESSION_MAX_ACCOUNTED_TIME = 72000

const MAX_FOCUS_SESSION_POINTS = FOCUS_SESSION_MAX_ACCOUNTED_TIME * 0.1

const IMPACT_POINTS = 72

const POINTS_BY_MILLISECOND = 0.001

const MAX_DAY_POINTS = 36000

const WHITE_DWARF = 10800
const RED_GIANT = 18000
const SUPER_NOVA = 24000
const NEUTRON_STAR = 30000
const BLACK_HOLE = MAX_DAY_POINTS

export {
  BLACK_HOLE,
  FOCUS_SESSION_MAX_ACCOUNTED_TIME,
  IMPACT_POINTS,
  MAX_DAY_POINTS,
  MAX_FOCUS_SESSION_POINTS,
  NEUTRON_STAR,
  POINTS_BY_MILLISECOND,
  RED_GIANT,
  SUPER_NOVA,
  WHITE_DWARF,
}
